### ISSUE TITLE
Implicit type casting for conditionals not explained

### ISSUE THREAD

**Issue by luuklsl** [schmettow/PfP_Book#21]
When looking at exercise 3.6.4, people first get a hands on interaction with the implicit typecasting happening in Python conditionals. For most people it is not clear what is happening in the code below. 

`x = 5
y = 0

if x >= 5 and y != False:
    print(y/x)`

Possible fix: explain about implicit typecasting that is happening in conditionals and why 0 == False (and almost all else is true)

**Comment by schmettow** [comment]
I added an explanation to 3.1. I quickly discovered that Boolean - int conversion is a complete mess in Python. So: always be explicit!
