### ISSUE TITLE
Errors when trying to knit

### ISSUE THREAD

**Issue by Smirkena** [schmettow/PfP_Book#3]
@schmettow 
I can no longer knit the .Rmd chapter files. Whenever I try to knit a chapter, **all** code chunks are executed, including the ones I marked with `eval=FALSE`. I frequently include errorneous Python code on purpose to emphasize explanations or as part of exercises.

Do you have any idea why knitting including errorneous code chunks worked before, but doesn't anymore?

**Comment by schmettow** [comment]
I cannot reproduce your problem. However, if the code is *syntactically* invalid, it is the parser that throws error messages. All code in chunks is parsed in order to get syntax highlighting. In such a case, use a chunk with the engine left blank:
```{}
""This is syntactically invalid, but must not give an error message"
""Because it is syntactically invalid, it also cannot be parsed and highlighted""´
```

**Comment by Smirkena** [comment]
I can confirm that the parser is the culprit behind the error messages. I will use blank code chunks in the future!
